### ISSUE TITLE
Translate to [pt-br]: Review whole translation in the end

### ISSUE THREAD

**Issue by vdemario** [gobridge/bwag#21]
As I suggested in #20, I think we should review the whole pt-br translation after we finish it.

Different translators will have chosen to translate some terms in slightly different ways in each chapter. There's nothing wrong with that at first, but the final version should be consistent.

We may not need to track this with an issue, feel free to close this if you don't think this is necessary.

**Comment by aleborba** [comment]
:+1:

**Comment by guilhermebr** [comment]
:+1:

**Comment by carlisia** [comment]
O que estah faltando pra merge as traducoes?

**Comment by vdemario** [comment]
Honestamente, acho que nada. Eu li tudo por causa do workshop e acho q o material já tá ok como tá agora.

**Comment by carlisia** [comment]
Legal. Voce pode fazer o PR @vdemario?

**Comment by vdemario** [comment]
@carlisia acabei de mandar o PR
