### ISSUE TITLE
Translate to [pt-br] Chapter 2 (Go Makes Things Simple)

### ISSUE THREAD

**Issue by guilhermebr** [gobridge/bwag#3]

**Comment by maiconio** [comment]
Hello, @guilhermebr !

I translated chapter 2, here https://github.com/maiconio/bwag/tree/pt-br/pt-br/go_makes_things_simple

I have some questions. Should we change the folder and filenames, too? (i.e: go_makes_things_simple --> go_facilita_as_coisas)

Also, when I finish, should I PR directly here in the main project, or should I PR on your fork?

Thanks!

**Comment by guilhermebr** [comment]
Hi @maiconio,

Great! I think that folders can keep in english, I translated the summary to pt-br.

do a PR for gobridge/bwag in pt-br branch

Thank you!!

**Comment by guilhermebr** [comment]
Done by PR #16
